<a href="https://colab.research.google.com/github/prakhartiwari10/Colab-Notebooks/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim
scalar.shape

torch.Size([])

In [ ]:
vector = torch.tensor([7, 7])

In [ ]:
vector.ndim
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

### Random tensors

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.5528, 0.9470, 0.0910, 0.7010],
        [0.4240, 0.4358, 0.4736, 0.0218],
        [0.3575, 0.4872, 0.9846, 0.3979]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create a tensor of all ones
ones = torch.ones(size = (3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes
**Note:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch and deep learning:
  1. Tensors not right datatype
  2. Tensors not right shape
  3. Tensors not on the right device

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device=None,#(Could be "cpu"/"cuda")
                               requires_grad=False)

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
print(random_tensor)
print(f"Datatype 0f tensor: {random_tensor.dtype}")
print(f"Shape 0f tensor: {random_tensor.shape}")
print(f"Device 0f tensor: {random_tensor.device}")

tensor([[0.5528, 0.9470, 0.0910, 0.7010],
        [0.4240, 0.4358, 0.4736, 0.0218],
        [0.3575, 0.4872, 0.9846, 0.3979]])
Datatype 0f tensor: torch.float32
Shape 0f tensor: torch.Size([3, 4])
Device 0f tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication(element-wise)
* Division
* Matrix Multiplication

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor +10

tensor([11, 12, 13])

In [ ]:
tensor*10, tensor-10, torch.mul(tensor, 10), torch.add(tensor, 10)

(tensor([10, 20, 30]),
 tensor([-9, -8, -7]),
 tensor([10, 20, 30]),
 tensor([11, 12, 13]))

### Matrix multiplication

Two main ways of performing multiplication in neurl networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication ( dot product )

There are two main rules for matrix multiplication to satisfy:
1. The **inner dimensions** must match:
* `(3,2) @ (3,2)` won't work
* `(2, 3) @ (3, 2) ` will work
* `(3,2) @ (2, 3)` will work

In [ ]:
print(tensor, "*", tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.66 ms, sys: 128 µs, total: 2.79 ms
Wall time: 18.1 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 230 µs, sys: 44 µs, total: 274 µs
Wall time: 214 µs


tensor(14)

In [ ]:
#tensor_A = torch.tensor([[1, 2],
#                         [3, 4],
#                         [5, 6]])

#tensor_B = torch.tensor([[7, 10],
#                         [8, 11],
#                         [9, 12]])

#torch.mm(tensor_A, tensor_B) ## same as mm is same as matmul

To fix our tensor shape issues, we can manipulat4e the shape of one of our tensors using a transpose.

In [ ]:
tensor_B = tensor_B.T

In [ ]:
torch.mm(tensor_A, tensor_B)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

There are also functions like .mean, max, min, sum can be used like torch.mean(tensor_A) or like tensor_A.mean both there is also argmin and argmax or argmean which gives the index of the same

### Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orginal tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [ ]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x (because view of a tensor shares the same memory as the original)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
!nvidia-smi

Mon Apr 15 18:30:57 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1


## Putting tensors(and models) on the GPU

In [ ]:
import torch
# Create a tensor(default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

##4. Moving tensors back to CPU


In [ ]:
# If tensor is on GPU, can't transform it to Numpy
#tensor_on_gpu.numpy()

In [ ]:
# To fix the GPU tensor with Numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

## Exercises and extra-curriculum

In [ ]:
# See Exercises in https://www.learnpytorch.io/00_pytorch_fundamentals -- exercises(book)